"""Horizontal setup area and permanent side-by-side source / Gaussian previews."""
from datetime import datetime
from PySide6 import QtCore, QtWidgets
from . import core
from .viewer import Viewer


def build(window, image_class):
    w = window
    root = QtWidgets.QWidget(); root.setObjectName("Root"); w.setCentralWidget(root)
    page = QtWidgets.QVBoxLayout(root); page.setContentsMargins(18, 12, 18, 12); page.setSpacing(8)
    header = QtWidgets.QHBoxLayout()
    title = w.label("4DGS Workbench"); title.setStyleSheet("font-size: 25px; font-weight: 600;")
    header.addWidget(title); header.addStretch()
    w.training_check = w.button("Training Environment: Not Checked", w.open_training_environment)
    w.plugin_check = w.button("UE Plugin: Select Project", w.open_ue_plugin)
    w.check_button = w.button("Check GPU", w.check_environment)
    for item in (w.training_check, w.plugin_check, w.check_button): header.addWidget(item)
    w.environment_label = w.label("", muted=True); w.environment_label.hide()
    page.addLayout(header)
    split = QtWidgets.QSplitter(QtCore.Qt.Orientation.Vertical); page.addWidget(split, 1)
    top = QtWidgets.QScrollArea(); top.setWidgetResizable(True); top.setMinimumHeight(200)
    w.inputs = QtWidgets.QWidget(); w.inputs.setObjectName("Inputs"); top.setWidget(w.inputs)
    groups = QtWidgets.QHBoxLayout(w.inputs); groups.setContentsMargins(0, 0, 0, 0); groups.setSpacing(10)
    source = QtWidgets.QGroupBox("Source"); a = QtWidgets.QVBoxLayout(source)
    w.folder = QtWidgets.QLineEdit(); w.folder.setPlaceholderText("Capture dataset folder"); a.addWidget(w.folder)
    row = QtWidgets.QHBoxLayout()
    row.addWidget(w.button("Browse...", w.browse_dataset)); row.addWidget(w.button("Use Sample", w.use_sample)); a.addLayout(row)
    row = QtWidgets.QHBoxLayout(); row.addWidget(w.label("Temporal Stride")); w.stride = w.spin(1,1000,1); row.addWidget(w.stride)
    w.validate_button = w.button("Validate Dataset", w.validate); row.addWidget(w.validate_button); a.addLayout(row)
    w.data_info = w.label("Choose a completed capture dataset.", muted=True); w.data_info.setWordWrap(True); a.addWidget(w.data_info); a.addStretch()
    groups.addWidget(source, 1)
    training = QtWidgets.QGroupBox("Training"); a = QtWidgets.QGridLayout(training)
    w.preset = QtWidgets.QComboBox(); w.preset.addItems([*core.PRESETS,"Custom"])
    w.coarse = w.spin(1,10000,300); w.fine = w.spin(1,100000,3000); w.interval = w.spin(1,10000,500)
    w.grid = w.spin(3,300,50); w.sh = w.spin(0,3,3)
    w.background = QtWidgets.QComboBox(); w.background.addItems(["White","Black"])
    fields = [("Preset",w.preset),("Coarse Iterations",w.coarse),("Fine Iterations",w.fine),
        ("Checkpoint Every",w.interval),("Temporal Grid",w.grid),("SH Degree",w.sh),("Background",w.background)]
    for index,(label,widget) in enumerate(fields):
        row,col = divmod(index,2); a.addWidget(w.label(label),row,col*2); a.addWidget(widget,row,col*2+1)
    w.opacity = QtWidgets.QCheckBox("Animate Opacity (experimental)"); a.addWidget(w.opacity,4,0,1,4)
    w.applying_preset = False; w.preset.currentTextChanged.connect(w.apply_preset)
    w.coarse.valueChanged.connect(w.mark_custom); w.fine.valueChanged.connect(w.mark_custom)
    groups.addWidget(training, 2)
    output = QtWidgets.QGroupBox("Output"); a = QtWidgets.QVBoxLayout(output)
    w.output = QtWidgets.QLineEdit(str(core.RUNS)); a.addWidget(w.output)
    a.addWidget(w.button("Choose Output Folder...",w.browse_output))
    w.name = QtWidgets.QLineEdit("capture-"+datetime.now().strftime("%m%d-%H%M%S")); w.name.setPlaceholderText("New run name"); a.addWidget(w.name)
    w.history = QtWidgets.QComboBox(); a.addWidget(w.history)
    row = QtWidgets.QHBoxLayout(); row.addWidget(w.button("Load Selected",w.load_selected)); row.addWidget(w.button("Open Run...",w.browse_run)); a.addLayout(row)
    groups.addWidget(output, 1); split.addWidget(top)
    bottom = QtWidgets.QWidget(); b = QtWidgets.QVBoxLayout(bottom); b.setContentsMargins(0,4,0,0); b.setSpacing(8)
    actions = QtWidgets.QHBoxLayout()
    w.start_button = w.button("Start Training",w.start_training,primary=True)
    w.resume_button = w.button("Resume Run",w.resume); w.stop_button = w.button("Stop & Save",w.stop)
    w.force_button = w.button("Force Stop...",w.force_stop); w.force_button.hide()
    for item in (w.start_button,w.resume_button,w.stop_button,w.force_button): actions.addWidget(item)
    w.run_info = w.label("No run selected",muted=True); actions.addWidget(w.run_info,1)
    w.render_button = w.button("Export Video",w.render_result); w.video_button = w.button("Open Video",w.open_video)
    w.ue_button = w.button("Add to Unreal...",w.add_to_unreal)
    for item in (w.render_button,w.video_button,w.ue_button,w.button("Run Folder",w.open_run_folder)): actions.addWidget(item)
    b.addLayout(actions)
    metrics = QtWidgets.QHBoxLayout(); w.metrics = {}
    for key,label in (("stage","Stage"),("iteration","Iteration"),("loss","Loss"),("psnr","Train PSNR"),("points","Gaussians")):
        metrics.addWidget(w.label(label,muted=True)); value = w.label("--"); w.metrics[key] = value; metrics.addWidget(value); metrics.addSpacing(14)
    metrics.addStretch(); b.addLayout(metrics)
    w.progress = QtWidgets.QProgressBar(); w.progress.setRange(0,100); w.progress.setValue(0); w.progress.setTextVisible(False); b.addWidget(w.progress)
    w.status = w.label("Choose a capture folder to get started.",muted=True); w.status.setWordWrap(True); b.addWidget(w.status)
    previews = QtWidgets.QSplitter(QtCore.Qt.Orientation.Horizontal)
    left = QtWidgets.QFrame(); left.setObjectName("Card"); c = QtWidgets.QVBoxLayout(left)
    bar = QtWidgets.QHBoxLayout(); bar.addWidget(w.label("SOURCE SEQUENCE")); bar.addStretch()
    w.camera = QtWidgets.QComboBox(); w.camera.currentIndexChanged.connect(w.update_frame_list); bar.addWidget(w.camera); c.addLayout(bar)
    w.source_view = image_class("Load a dataset to inspect source images"); c.addWidget(w.source_view,1)
    bar = QtWidgets.QHBoxLayout(); w.play = w.button("Play",w.toggle_play); bar.addWidget(w.play)
    w.slider = QtWidgets.QSlider(QtCore.Qt.Orientation.Horizontal); w.slider.valueChanged.connect(w.show_frame); bar.addWidget(w.slider,1)
    w.frame_label = w.label("No frames",muted=True); bar.addWidget(w.frame_label); c.addLayout(bar)
    right = QtWidgets.QFrame(); right.setObjectName("Card"); c = QtWidgets.QVBoxLayout(right)
    c.addWidget(w.label("4DGS PREVIEW")); w.viewer = Viewer(w); c.addWidget(w.viewer,1)
    w.viewer.time_changed.connect(w.sync_source_time)
    previews.addWidget(left); previews.addWidget(right); previews.setSizes([600,600]); b.addWidget(previews,1)
    log_bar = QtWidgets.QHBoxLayout(); w.log_toggle = QtWidgets.QToolButton(); w.log_toggle.setText("Show Log"); w.log_toggle.setCheckable(True)
    log_bar.addWidget(w.log_toggle); log_bar.addStretch(); b.addLayout(log_bar)
    w.log = QtWidgets.QPlainTextEdit(); w.log.setReadOnly(True); w.log.setMaximumBlockCount(1500); w.log.setMaximumHeight(120); w.log.hide()
    w.log_toggle.toggled.connect(w.log.setVisible); w.log_toggle.toggled.connect(lambda checked:w.log_toggle.setText("Hide Log" if checked else "Show Log")); b.addWidget(w.log)
    split.addWidget(bottom); split.setSizes([260,600]); split.setStretchFactor(0,0); split.setStretchFactor(1,1)
    # Offline export options are independent of the permanent preview panes.
    w.render_mode = QtWidgets.QComboBox(w); w.render_mode.addItems(["First validation camera","Orbit (160 frames)"]); w.render_mode.hide()
    w.fps = w.spin(1,120,24); w.fps.setParent(w); w.fps.hide()
    w.result_view = image_class(""); w.result_view.setParent(w); w.result_view.hide()
    w.play_timer = QtCore.QTimer(w); w.play_timer.timeout.connect(lambda:w.slider.setValue((w.slider.value()+1)%max(1,w.slider.maximum()+1)))
    w.folder.textChanged.connect(w.invalidate_dataset); w.stride.valueChanged.connect(w.invalidate_dataset)
    w.background.currentTextChanged.connect(lambda:w.show_frame(w.slider.value()))
    for item in (w.resume_button,w.stop_button,w.render_button,w.video_button,w.ue_button): item.setEnabled(False)
